// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robot builder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "DriveSubsystem.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/PlayerDrive.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

DriveSubsystem::DriveSubsystem() : Subsystem("DriveSubsystem") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    leftControl = RobotMap::driveSubsystemLeftControl;
    leftEncoder = RobotMap::driveSubsystemLeftEncoder;
    leftDrive = RobotMap::driveSubsystemLeftDrive;
    rightEncoder = RobotMap::driveSubsystemRightEncoder;
    rightControl = RobotMap::driveSubsystemRightControl;
    rightDrive = RobotMap::driveSubsystemRightDrive;
    rearLeft = RobotMap::driveSubsystemRearLeft;
    rearRight = RobotMap::driveSubsystemRearRight;
    backDrive = RobotMap::driveSubsystemBackDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void DriveSubsystem::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new PlayerDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Drive(std::shared_ptr<Joystick> left, std::shared_ptr<Joystick> right){
	Robot::driveSubsystem->leftControl->Set(left->GetY());
	Robot::driveSubsystem->rightControl->Set(-right->GetY());
	Robot::driveSubsystem->backDrive->TankDrive(left->GetY(), right->GetY());
}

void Drive(float left, float right){
	Robot::driveSubsystem->leftControl->Set(left);
	Robot::driveSubsystem->rightControl->Set(-right);
	Robot::driveSubsystem->backDrive->TankDrive(left, right);
}

void Stop(){
	Robot::driveSubsystem->leftControl->Set(0);
	Robot::driveSubsystem->rightControl->Set(0);
	Robot::driveSubsystem->backDrive->StopMotor();
}
