// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robot builder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "DriveSubsystem.h"
#include "../RobotMap.h"
#include "../Commands/DriveC.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

DriveSubsystem::DriveSubsystem() : Subsystem("DriveSubsystem") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    leftControl = RobotMap::driveSubsystemLeftControl;
    leftEncoder = RobotMap::driveSubsystemLeftEncoder;
    rightEncoder = RobotMap::driveSubsystemRightEncoder;
    rightControl = RobotMap::driveSubsystemRightControl;
    rearLeft = RobotMap::driveSubsystemRearLeft;
    rearRight = RobotMap::driveSubsystemRearRight;
    drive = RobotMap::driveSubsystemDrive;

    dist = 0;
    lastMult = 1.715;
    multiplier = 1.715;

    changeSensitivity = false;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void DriveSubsystem::InitDefaultCommand() {
    // Set the default command for a subsystem here.
     SetDefaultCommand(new DriveC());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}



void DriveSubsystem::Drive(std::shared_ptr<Joystick> left, std::shared_ptr<Joystick> right){
	leftControl->Set(left->GetY());
	rightControl->Set(-right->GetY());

	if (changeSensitivity == false){
		drive->TankDrive(left->GetY(), right->GetY());
	}else if (changeSensitivity == true){
		float leftSquare = left->GetY() * left->GetY();
		float rightSquare = right->GetY() * right->GetY();

		if (left->GetY() < 0){
			leftSquare = -leftSquare;
		}
		if (right->GetY() < 0){
			rightSquare = -rightSquare;
		}

		SmartDashboard::PutNumber("Squared left:", leftSquare);
		SmartDashboard::PutNumber("Squared right:", rightSquare);

		drive->TankDrive(leftSquare, rightSquare);
	}
}
void DriveSubsystem::Drive(float left, float right){
	//leftControl->Set(left);
	//rightControl->Set(-right);
	drive->TankDrive(left, right);
}
void DriveSubsystem::Stop(){
	//leftControl->Set(0);
	//rightControl->Set(0);
	drive->StopMotor();
}

double DriveSubsystem::CalculateRotations(float distance){
	return distance/(4*M_PI);
}

float DriveSubsystem::CalculateDistance(int ticks){
	return (ticks/ticksPerRev)*(4*M_PI);
}

void DriveSubsystem::sensitivityFalse(){
	changeSensitivity = false;
}
void DriveSubsystem::sensitivityTrue(){
	changeSensitivity = true;
}

void DriveSubsystem::driveStraight(std::shared_ptr<Joystick> left, std::shared_ptr<Joystick> right){
	double joyLeft = left->GetY();
	double joyRight = right->GetY();

	multiplier = ((joyRight / joyLeft) / (std::abs(rightEncoder->Get()) / std::abs(leftEncoder->Get())));

	if (lastMult ==  1000000.0){
		leftControl->Set(joyLeft / multiplier);
		lastMult = multiplier;
	}else{
		multiplier = (multiplier + lastMult) / 2;

		lastMult = multiplier;

		leftControl->Set(joyLeft / multiplier);
	}

	rightControl->Set(joyRight);

	drive->TankDrive(leftControl->Get(), rightControl->Get());
}

void DriveSubsystem::driveStraight(double left, double right){
	rightControl->Set(-right);
	leftControl->Set(left);

	if (rightEncoder->Get() != 0.0 && leftEncoder->Get() != 0.0){
		multiplier = ((right / left) / ((double) std::abs(rightEncoder->Get()) / (double) std::abs(leftEncoder->Get())));


		if (lastMult == 1.715){
			leftControl->Set(left * multiplier);

			lastMult = multiplier;
		}else{
			multiplier = (multiplier + lastMult) / 2.0;

			lastMult = multiplier;

			leftControl->Set(left * multiplier);
		}

	}

	drive->TankDrive(leftControl->Get(), rightControl->Get(), false);
}

void DriveSubsystem::slowLeft(){

}

void DriveSubsystem::slowRight(){

}
