// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/Def1.h"
#include "Commands/Def2.h"
#include "Commands/Def3.h"
#include "Commands/Def4.h"
#include "Commands/Def5.h"
#include "Commands/Def6.h"
#include "Commands/Def7.h"
#include "Commands/Def8.h"
#include "Commands/Def9.h"
#include "Commands/DriveC.h"
#include "Commands/Pos1.h"
#include "Commands/Pos2.h"
#include "Commands/Pos3.h"
#include "Commands/Pos4.h"
#include "Commands/Pos5.h"
#include "Commands/extend.h"
#include "Commands/retract.h"
#include "Commands/rotateIn.h"
#include "Commands/rotateOut.h"
#include "Commands/fireC.h"
#include "Commands/loadC.h"
#include "Commands/releaseC.h"
#include "Commands/manualLoaderToggle.h"
#include "Commands/manualLatchToggle.h"
#include "Commands/sensitivityFalse.h"
#include "Commands/sensitivityTrue.h"
#include "Commands/AutoCG.h"
#include "Commands/DriveReverse.h"
#include "Commands/DriveReverseSlow.h"
#include "Commands/Def1CG.h"
#include "Commands/Def2CG.h"
#include "Commands/Def3CG.h"
#include "Commands/Def4CG.h"
#include "Commands/Def5CG.h"
#include "Commands/Def6CG.h"
#include "Commands/Def7CG.h"
#include "Commands/Def8CG.h"
#include "Commands/Def9CG.h"
#include "Commands/After1CG.h"
#include "Commands/After2CG.h"
#include "Commands/After3CG.h"
#include "Commands/After4CG.h"
#include "Commands/After5CG.h"
#include "Commands/Before1CG.h"
#include "Commands/Before2CG.h"
#include "Commands/Before3CG.h"
#include "Commands/intakeDown.h"
#include "Commands/intakeUp.h"
#include "Commands/CalibrateCG.h"
#include "Commands/UnlockShooter.h"
#include "Commands/SlowTurnLeft.h"
#include "Commands/SlowTurnRight.h"
#include "Commands/SmallReverse.h"
#include "Commands/FireCG.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	//joysticks
    joystickLeft.reset(new Joystick(0));
    joystickRight.reset(new Joystick(1));
    joystickShooter.reset(new Joystick(2));

    //left joystick buttons
    joystickLB1.reset(new JoystickButton(joystickLeft.get(), 1));
    	joystickLB1->WhenPressed(new FireCG());
    joystickLB2.reset(new JoystickButton(joystickLeft.get(), 2));
    	joystickLB2->WhenPressed(new intakeDown());
    joystickLB3.reset(new JoystickButton(joystickLeft.get(), 3));
    	joystickLB3->WhenPressed(new intakeUp());
    joystickLB10.reset(new JoystickButton(joystickLeft.get(), 10));
    	joystickLB10->WhenPressed(new manualLoaderToggle());
    joystickLB11.reset(new JoystickButton(joystickLeft.get(), 11));
    	joystickLB11->WhenPressed(new manualLatchToggle());

    //right joystick buttons
    joystickRB1.reset(new JoystickButton(joystickRight.get(), 1));
    joystickRB2.reset(new JoystickButton(joystickRight.get(), 2));
    	joystickRB2->WhileHeld(new rotateIn());
    joystickRB3.reset(new JoystickButton(joystickRight.get(), 3));
    	joystickRB3->WhileHeld(new rotateOut());
    joystickRB4.reset(new JoystickButton(joystickRight.get(), 4));
    	joystickRB4->WhileHeld(new extend());
    joystickRB5.reset(new JoystickButton(joystickRight.get(), 5));
    	joystickRB5->WhileHeld(new retract());
    joystickRB11.reset(new JoystickButton(joystickRight.get(), 11));
    	 joystickRB11->WhenPressed(new CalibrateCG());

    //shooter joystick buttons
    joystickSB1.reset(new JoystickButton(joystickShooter.get(), 1));
    	joystickSB1->WhenPressed(new FireCG());
    joystickSB2.reset(new JoystickButton(joystickShooter.get(), 2));
    	joystickSB2->WhileHeld(new UnlockShooter());
    joystickSB3.reset(new JoystickButton(joystickShooter.get(), 3));
    	joystickSB3->WhileHeld(new SlowTurnLeft());
    joystickSB4.reset(new JoystickButton(joystickShooter.get(), 4));
    	joystickSB4->WhileHeld(new SlowTurnRight());
    joystickSB5.reset(new JoystickButton(joystickShooter.get(), 5));
    	joystickSB5->WhenPressed(new loadC());
    joystickSB6.reset(new JoystickButton(joystickShooter.get(), 6));
    	joystickSB6->WhenPressed(new releaseC());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getJoystickLeft() {
   return joystickLeft;
}

std::shared_ptr<Joystick> OI::getJoystickRight() {
   return joystickRight;
}

std::shared_ptr<Joystick> OI::getJoystickShooter(){
	return joystickShooter;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
