// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Def1.h"
#include "Commands/Def2.h"
#include "Commands/Def3.h"
#include "Commands/Def4.h"
#include "Commands/Def5.h"
#include "Commands/Def6.h"
#include "Commands/Def7.h"
#include "Commands/Def8.h"
#include "Commands/Def9.h"
#include "Commands/DriveC.h"
#include "Commands/Pos1.h"
#include "Commands/Pos2.h"
#include "Commands/Pos3.h"
#include "Commands/Pos4.h"
#include "Commands/Pos5.h"
#include "Commands/WindowForward.h"
#include "Commands/WindowReverse.h"
#include "Commands/extend.h"
#include "Commands/retract.h"
#include "Commands/rotateIn.h"
#include "Commands/rotateOut.h"
#include "Commands/fireC.h"
#include "Commands/loadC.h"
#include "Commands/releaseC.h"
#include "Commands/manualLoaderToggle.h"
#include "Commands/manualLatchToggle.h"
#include "Commands/sensitivityFalse.h"
#include "Commands/sensitivityTrue.h"
#include "Commands/After1.h"
#include "Commands/After2.h"
#include "Commands/After3.h"
#include "Commands/After4.h"
#include "Commands/After5.h"
#include "Commands/AutoCG.h"
#include "Commands/DriveReverse.h"
#include "Commands/DriveReverseSlow.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystickRight.reset(new Joystick(1));
    joystickLeft.reset(new Joystick(0));
    
    //right joystick buttons
    joystickRB1.reset(new JoystickButton(joystickRight.get(), 1));
    	joystickRB1->WhileHeld(new WindowReverse());
    joystickRB2.reset(new JoystickButton(joystickRight.get(), 2));
    	joystickRB2->WhileHeld(new WindowForward());

    //left joystick buttons
    joystickLB11.reset(new JoystickButton(joystickLeft.get(), 11));
    	joystickLB11->WhenPressed(new manualLatchToggle());
    joystickLB10.reset(new JoystickButton(joystickLeft.get(), 10));
    	joystickLB10->WhenPressed(new manualLoaderToggle());
    joystickLB3.reset(new JoystickButton(joystickLeft.get(), 3));
    	joystickLB3->WhenPressed(new releaseC());
    joystickLB2.reset(new JoystickButton(joystickLeft.get(), 2));
    	joystickLB2->WhenPressed(new loadC());
    joystickLB1.reset(new JoystickButton(joystickLeft.get(), 1));
    	joystickLB1->WhenPressed(new fireC());

    // SmartDashboard Buttons
    /*
    SmartDashboard::PutData("WindowReverse", new WindowReverse());
    SmartDashboard::PutData("WindowForward", new WindowForward());
    SmartDashboard::PutData("DriveC", new DriveC());
    SmartDashboard::PutData("Pos5", new Pos5());
    SmartDashboard::PutData("Pos4", new Pos4());
    SmartDashboard::PutData("Pos3", new Pos3());
    SmartDashboard::PutData("Pos2", new Pos2());
    SmartDashboard::PutData("Pos1", new Pos1());
    SmartDashboard::PutData("Def9", new Def9());
    SmartDashboard::PutData("Def8", new Def8());
    SmartDashboard::PutData("Def7", new Def7());
    SmartDashboard::PutData("Def6", new Def6());
    SmartDashboard::PutData("Def5", new Def5());
    SmartDashboard::PutData("Def4", new Def4());
    SmartDashboard::PutData("Def3", new Def3());
    SmartDashboard::PutData("Def2", new Def2());
    SmartDashboard::PutData("Def1", new Def1());
    */
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getJoystickLeft() {
   return joystickLeft;
}

std::shared_ptr<Joystick> OI::getJoystickRight() {
   return joystickRight;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
