// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Joystick> joystickRight;
	std::shared_ptr<Joystick> joystickLeft;
	std::shared_ptr<Joystick> joystickShooter;
	//buttons for right joystick
	std::shared_ptr<JoystickButton> joystickRB1;
	std::shared_ptr<JoystickButton> joystickRB2;
	std::shared_ptr<JoystickButton> joystickRB3;
	std::shared_ptr<JoystickButton> joystickRB4;
	std::shared_ptr<JoystickButton> joystickRB5;
	std::shared_ptr<JoystickButton> joystickRB11;
	//buttons for left joystick
	std::shared_ptr<JoystickButton> joystickLB1;
	std::shared_ptr<JoystickButton> joystickLB2;
	std::shared_ptr<JoystickButton> joystickLB3;
	std::shared_ptr<JoystickButton> joystickLB11;
	std::shared_ptr<JoystickButton> joystickLB10;
	//buttons for shooter joystick (FULL)
	std::shared_ptr<JoystickButton> joystickSB1;
	std::shared_ptr<JoystickButton> joystickSB2;
	std::shared_ptr<JoystickButton> joystickSB3;
	std::shared_ptr<JoystickButton> joystickSB4;
	std::shared_ptr<JoystickButton> joystickSB5;
	std::shared_ptr<JoystickButton> joystickSB6;
	std::shared_ptr<JoystickButton> joystickSB7;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> getJoystickLeft();
	std::shared_ptr<Joystick> getJoystickRight();
	std::shared_ptr<Joystick> getJoystickShooter();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
