// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousCommand.h"
#include "Subsystems/ControlSS.h"
#include "Subsystems/DriveSubsystem.h"
#include "SmartDashboard/SmartDashboard.h"

#include "Subsystems/ControlSS.h"
#include "Commands/Pos1.h"
#include "Commands/Pos2.h"
#include "Commands/Pos3.h"
#include "Commands/Pos4.h"
#include "Commands/Pos5.h"
#include "Commands/Def1.h"
#include "Commands/Def2.h"
#include "Commands/Def3.h"
#include "Commands/Def4.h"
#include "Commands/Def5.h"
#include "Commands/Def6.h"
#include "Commands/Def7.h"
#include "Commands/Def8.h"
#include "Commands/Def9.h"
#include "Commands/DriveC.h"
#include "Commands/extend.h"
#include "Commands/retract.h"
#include "Commands/rotateIn.h"
#include "Commands/rotateOut.h"
#include "Commands/fireC.h"
#include "Commands/loadC.h"
#include "Commands/releaseC.h"
#include "Commands/manualLoaderToggle.h"
#include "Commands/manualLatchToggle.h"
#include "Commands/sensitivityFalse.h"
#include "Commands/sensitivityTrue.h"
#include "Commands/AutoCG.h"
#include "Commands/DriveReverse.h"
#include "Commands/DriveReverseSlow.h"
#include "Commands/Def1CG.h"
#include "Commands/Def2CG.h"
#include "Commands/Def3CG.h"
#include "Commands/Def4CG.h"
#include "Commands/Def5CG.h"
#include "Commands/Def6CG.h"
#include "Commands/Def7CG.h"
#include "Commands/Def8CG.h"
#include "Commands/Def9CG.h"
#include "Commands/After1CG.h"
#include "Commands/After2CG.h"
#include "Commands/After3CG.h"
#include "Commands/After4CG.h"
#include "Commands/After5CG.h"
#include "Commands/Before1CG.h"
#include "Commands/Before2CG.h"
#include "Commands/Before3CG.h"
#include "Commands/intakeDown.h"
#include "Commands/intakeUp.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot : public IterativeRobot {
public:
	std::unique_ptr<CommandGroup> autonomousCommand;
	static std::unique_ptr<OI> oi;
	LiveWindow *lw = LiveWindow::GetInstance();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static std::shared_ptr<ControlSS> controlSS;
    static std::shared_ptr<DriveSubsystem> driveSubsystem;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    //create empty commands to hold the options chosen
    Command* temp;
    Command* temp2;
    Command* temp3;
    Command* temp4;

    virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestPeriodic();
};
#endif
